### ISSUE TITLE
Case sensetivity 

### ISSUE THREAD

**Issue by mrokhfrooz** [PMEAL/OpenPNM-Examples#3]
Vin has been defined as " Vin = 1" and the following commend :
Seff.set_boundary_conditions(bctype='Dirichlet', bcvalue=VIn, pores=pn.pores('top'))
is not run-able and would result this Error
NameError: name 'VIn' is not defined

**Comment by jgostick** [comment]
If you've cut and pasted your code directly then you've got a case problem
Vin vs VIn.  Lower vs upper case i.

**Comment by jgostick** [comment]
Thanks for pointing this out.  I spent the afternoon setting up TravisCI and Pytest so now ALL our examples are tested!! This will be a huge bonus for us since having out of date and incorrect examples has been an issue right from the beginning.  I hope to see a PR from you with an example very soon :-D
