### ISSUE TITLE
How to run 'MixedPercolation' successfully?

### ISSUE THREAD

**Issue by IATBYSIC** [PMEAL/OpenPNM-Examples#32]
Dear Dr. @jgostick 
I am a Phd student studying at Georgia Tech and majoring in geotechnical engineering. I am now learning OpenPNM by myself. As I am not quite familiar with the Python language, so I did some simulations according to the instructions(examples) that can be found online, such as the InvasionPercolaton and OridinaryPercolation(https://github.com/PMEAL/OpenPNM-Examples). However, I have been trying to run MixedPercolation for a while, but I still can't run it successfully. The error is shown as follows: KeyError: 'pore.capillary_pressure'. Could you please tell me where I can find the instructions about how to run the code, "MixedPercolation"?  Look forward to you reply. Thanks a lot!

**Comment by IATBYSIC** [comment]
Hi @TomTranter , many thanks for your reply! I have tried your solution and it worked. But new errors appeared and I will keep working on it. Meanwhile, I will look forward to seeing your examples online. Also, thanks for your and your teammates' great  job to provide us so many valuable codes and files, I benefited from them lot!

**Comment by TomTranter** [comment]
Ah, I'm guessing because some of the geometry models may not be there. To be fair it's quite complex and formed the basis of my latest paper which you may have come across. https://link.springer.com/article/10.1007%2Fs11242-017-0973-2. If you personal message me your email I can send you a script that will work which generates a random network using the voronoi geometry and delaunay network if this is of interest. Again, it may not be if you're studying rocks. You're welcome for the codes.

**Comment by IATBYSIC** [comment]
Awesome! Thank you and I will message you my email soon.

**Comment by hefnymah** [comment]
Dear @TomTranter 
I am trying to use the mixedpercolation algorithm. I have the same issue. Would you please share the script example that worked with the generated random network?
Thanks a lot!

**Comment by TomTranter** [comment]
We now have examples on the different percolation algorithms here
https://github.com/PMEAL/OpenPNM/tree/master/examples/percolation
