### ISSUE TITLE
BC Example fails

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM-Examples#4]
@maghighi can you take a look at the example regarding setting boundary conditions and help undestand why it fails?  If you download this repo, run ``python run_tests`` you'll see that some odd error pops around line 128 regarding setting an array element with a sequence.  Any thoughts?

**Comment by maghighi** [comment]
In the corresponding file, there is a line: 
>>> alg.set_boundary_conditions(bctype='Neumann_group', pores=BC3_pores, mode='remove')

Based on the way the method works, this means that the user wants to keep the 'Neumann_group' label and prop but with the False and nan values in the BC3_pores. In the same file, this feature has been used for removing a group of Dirichlet pores. But if someone wants to remove all traces of a BC, then the following should be used:
>>> alg.set_boundary_conditions(bctype='Neumann_group', mode='remove')

With the above line, all tests will pass. But since the future users may make this mistake again, it seems an additional check for nans is required by the coefficient matrix. So, even if the user does not apply the 'remove' mode correctly, this error will not be shown. It will be easy to add. I'll make a pull request to OpenPNM.

**Comment by jgostick** [comment]
Thanks @maghighi, the problem is solved
