### ISSUE TITLE
What is the right way to run imbibition using any percolation algorithm?

### ISSUE THREAD

**Issue by haoliguo** [PMEAL/OpenPNM-Examples#60]
Dear @jgostick  @TomTranter and other contributors,

I am new to openpnm. My goal is to get relative permeability curves from imbibition process. In my system, water is wetting phase and oil is non-wetting phase. During imbibition, water invades an oil-filled network, so Sw should increase from 0 to (1-Sor), where Sor is residual oil saturation. In terms of Pc sequence during imbibition, it should have a decreasing order (from large Pc to small Pc) because the wetting phase (water) invades small throats first and invades larger pores/throats later, which is the opposite of drainage. 

I am following the "Tranter2017" example (Capillary Hysteresis in Neutrally Wettable Fibrous Media) to run imbibition. In my understanding, all of the percolation algorithms (OP, IP, MIP) are designed for drainage, which means Pc sequence has an increasing order because non-wetting phase invades larger pores first and fills smaller pores in the last during drainage. In this example, the imbibition simulation (IP_withdrawal) used MixedInvasionPercolatin and I assume the invading phase just fills in larger pores first? Is this correct?

My other questions are (1) why Pc is negative for the imbibition curve in the example? What does it mean if P_air > P_water during imbibition? 
(2) Shouldn't we somehow reverse the results from percolation algorithms to get the right Pc sequence and the right saturation of invading phase for imbibition simulation? What is the right way to do it? Are there any examples?

Thank you very much! Your help will be very much appreciated!!

**Comment by TomTranter** [comment]
I will answer this question more fully in an email to you but essentially the imbibition in a fibrous media which is neutrally wettable is not really imbibition in the classical sense. It requires positive pressure to inject water and negative pressure to suck it back out so there is hysteresis. This is caused by the curvature of the fibers and so injection and withdrawal are modeled like a double drainage process in my paper. If I can I will try and help you with your specific problem by email

**Comment by TomTranter** [comment]
We now have examples on percolation here
https://github.com/PMEAL/OpenPNM/tree/master/examples/percolation
