### ISSUE TITLE
 WARNING: Axes is already scaled to previously plotted data

### ISSUE THREAD

**Issue by Ahmedsf2019** [PMEAL/OpenPNM-Examples#62]
I'm doing the coordinates example in the Topotools page (https://openpnm.readthedocs.io/en/master/modules/topotools/index.html#topotools-index):-
I receive the following massage
 WARNING: Axes is already scaled to previously plotted data
    SOURCE: openpnm.topotools.topotools._scale_3d_axes
    TIME STAMP: 2019-07-17 17:18:19,051

The example is as follows: 
>>> import openpnm as op
>>> pn = op.network.Cubic(shape=[10, 10, 3])
>>> pn.add_boundary_pores()
>>> Ps = pn.pores('internal')
>>> # Create figure showing internal pores
>>> fig = op.topotools.plot_coordinates(pn, pores=Ps, c='b')
>>> Ps = pn.pores('*boundary')
>>> # Pass existing fig back into function to plot boundary pores
>>> fig = op.topotools.plot_coordinates(pn, pores=Ps, fig=fig, c='r')

**Comment by jgostick** [comment]
That warning is not important.  It's really just there to tell you that the plot will not be scaled properly.  The first figure is scaled so that it shows only the points that it receives, in a zoomed in way, so the next time that figure is used it is not rescaled and hence some points might not show up.  

I agree that this error is not helpful.  The solution would be to add an optional argument to to the functions, like ``zoom=True`` meaning it centers the view on only the given points (the current behavior), and ``zoom=False`` meaning it scales the axis to fit the entire domain.  Would that make sense to you?

**Comment by jgostick** [comment]
It should display still.  I'm not sure why that would happen.  Maybe you have some setting out of whack in your environment that matplotlib plots are not automatically displayed?  You could try plt.show().  You can also set interactive mode to on with plt.ion().  In jupyter notebooks there is an option to switch between different graph formats...I think something like "%matplotlib notebook" vs "%matplotlib inline".

**Comment by crflucifer** [comment]
WiW, I do not find the effective way to get the figure in Paraview  such as the  
![image](https://user-images.githubusercontent.com/37199393/72320180-1ae2d600-36dc-11ea-9ffd-9c23c3a13158.png)
I can not show the diameter of pores and throats. this is my figure in paraview.
![image](https://user-images.githubusercontent.com/37199393/72320440-a5c3d080-36dc-11ea-88e0-657695d17853.png)

**Comment by jgostick** [comment]
https://openpnm.readthedocs.io/en/master/getting_started/visualize_in_paraview.html
